vich_uploader:
    db_driver: orm        # or mongodb or phpcr - default db driver
    twig: true            # set to false to disable twig integration
    form: true            # set to false to disable form integration
    storage: file_system  # or gaufrette or flysystem
    metadata:
        auto_detection: true
        cache: file
        type: attribute   
    mappings:
        fichiers:
            uri_prefix: /fichier/
            upload_destination: '%kernel.project_dir%/public/fichier/'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 50 }

